### ISSUE TITLE
New Game menu crashing

### ISSUE THREAD

**Issue by fixator10** [robotboy655/gmod-lua-menu#10]
MENU ERROR: lua/menu/custom/new_game.lua:266: attempt to index global 'g_MapList' (a nil value) 
lua/menu/custom/new_game.lua:266 [Update] 
lua/menu/custom/new_game.lua:128 [Init] 
lua/includes/extensions/client/panel/scriptedpanels.lua:153 [Create] 
lua/menu/custom/mainmenu.lua:193 [OpenNewGameMenu] 
lua/menu/custom/main.lua:80 [DoClick] 
lua/vgui/dlabel.lua:218 []

No "back to menu button" and on starting server console says "No map selected", then "New Game menu" "ghosting" on background

**Comment by robotboy655** [comment]
Update your menu.

**Comment by fixator10** [comment]
I validated my gmod, it was missing 177 files, redownloaded and reinstalled menu, but still have this issue:

![2016-02-23_00001](https://cloud.githubusercontent.com/assets/11073934/13251336/fac10d22-da48-11e5-8657-42dccd5c559e.jpg)
![2016-02-23_00003](https://cloud.githubusercontent.com/assets/11073934/13251349/147c5852-da49-11e5-92f9-794ddfb32b81.jpg)
No maps here
![2016-02-23_00004](https://cloud.githubusercontent.com/assets/11073934/13251352/1ee5cc7e-da49-11e5-9a0d-92eaf63111c3.jpg)
After starting server via "Start Game"
![2016-02-23_00005](https://cloud.githubusercontent.com/assets/11073934/13251364/3045bd4e-da49-11e5-909d-687a50b4e62f.jpg)
![2016-02-23_00006](https://cloud.githubusercontent.com/assets/11073934/13251367/33e0438e-da49-11e5-8d4e-fc44887cc555.jpg)
And "ghosted" menu on background

**Comment by robotboy655** [comment]
Apparently I forgot to Sync the commit I made 4 month ago that fixes this. OOPS.
