### ISSUE TITLE
Cannot select map without going into develpoer mode.

### ISSUE THREAD

**Issue by roryyamm** [robotboy655/gmod-lua-menu#11]
Fantastic patch, really fixed up gmod, and I like the aesthetic of it.
However, it only works if I switch to the _developer_ version.
Otherwise, I cannot select maps.
running: Ubuntu 16.04 LTS w/ Common Desktop Environment (although that should not be a problem here), with an Intel Ironlake mobile G.P.U. Lenovo/IBM Thinkpad x201.

**Comment by robotboy655** [comment]
https://github.com/robotboy655/gmod-lua-menu/commit/a4d4eb7c9d6fe3f1abe66af01208ae656cf2d90f

**Comment by roryyamm** [comment]
Thank you. Now it is as close to perfect a fix I can find.
