### ISSUE TITLE
Engine Error (File Not Found Error)

### ISSUE THREAD

**Issue by RadsammyT** [robotboy655/gmod-lua-menu#15]
The message that points this out is "Couldn't include file 'includs/init_menu.lua' (File not found) (<nowhere>)

This isn't a compatibility issue. Is there anything to do you can fix?
Using Mac OSX.
Crashed Thread:        0  AwesomiumBrowserMain  Dispatch queue: com.apple.main-thread
When validated, it says 266 items in the custom failed to be validated after the process ended.

**Comment by robotboy655** [comment]
Verify your game, don't edit any files.

**Comment by RadsammyT** [comment]
I meant the Lua addon itself, not GMod's files in whole.

**Comment by robotboy655** [comment]
???

This addon does not modify the file "includes/init_menu.lua" in any way.
There is no such file as "includs/init_menu.lua" and there is no such folder as "includs" in this addon or base game.
Whatever is happening to you, its not caused by this addon.
