### ISSUE TITLE
Server Browser [Not Urgent]

### ISSUE THREAD

**Issue by AnthonyFuller** [robotboy655/gmod-lua-menu#16]
When will you add an actual server browser instead of the default source one?

**Comment by robotboy655** [comment]
I don't know. Chances are never. The default Source Engine server browser is an "actual browser", it had worked for decades for people.

I don't see anything wrong with it that warrants an immediate Lua replacement,
And besides this menu is barely used by anyone for me to spend time on it forcibly.
