### ISSUE TITLE
Looking for maps only in gmod directory

### ISSUE THREAD

**Issue by SupinePandora43** [robotboy655/gmod-lua-menu#17]
if you try to play on maps from source-engine content (`GarrysMod/garrysmod/cfg/mount.cfg`) lua menu dont find it!

**Comment by robotboy655** [comment]
Should be fixed by https://github.com/robotboy655/gmod-lua-menu/commit/a44ef3dcb1a5c533cc734856347709e44455fc24, update your installation.

**Comment by SupinePandora43** [comment]
@robotboy655 , when starting new game, pick "2 players", and group of checkboxes ("Local server", "(Translated)", "(Translated): only friends") broken because "Local server" and "(Translated)" can be enabled at once
