### ISSUE TITLE
Can't start MP servers

### ISSUE THREAD

**Issue by mish1git** [robotboy655/gmod-lua-menu#19]
I can't start P2P servers from the New Game menu. Whenever I try it ends up being a SP game

System details:
Pop-OS 21.04
Intel Core i5-7500
GTX 1650 Super
24 GB RAM

I'm running the game on Steam Proton.

**Comment by robotboy655** [comment]
What makes you think its a singleplauer game? I have just tested and there are no problems. If people can't join it, it's an issue with either Proton (so try native), or your network configuration.

![image](https://user-images.githubusercontent.com/3299036/126898853-ca55d0f6-60cd-4881-8b75-a9c676e4cd6d.png)
