### ISSUE TITLE
Can't start Garry's Mod

### ISSUE THREAD

**Issue by ItssShir0** [robotboy655/gmod-lua-menu#21]
I can't start Garry's Mod. Im executing the game from a Monterey Macbook Air with m1 chipset and to start it i changed to x64 bits version and executed it with -nochromium and when i try to execute the game the game loads but instead of getting me to the menu i get a blue screen.

**Comment by robotboy655** [comment]
This is not the place to complain about Garry's Mod issues.

**Comment by ItssShir0** [comment]
> This is not the place to complain about Garry's Mod issues.

I didn't express myself well, i didn't have the menu so I tried to do what is in this thread and when i used it my screen went blue and a non html menu didn't appear
