### ISSUE TITLE
Blue Screen when starting gmod with the lua and materials

### ISSUE THREAD

**Issue by ItssShir0** [robotboy655/gmod-lua-menu#22]
I can't start Garry's Mod. Im executing the game from a Monterey Macbook Air with m1 chipset and to start it i changed to x64 bits version and executed it with -nochromium and when i try to execute the game with the non html menu that you uploaded here the game loads but instead of getting me to the non-html menu i get a blue screen.

**Comment by robotboy655** [comment]
Sounds like you are not getting to the menu at all. Using `-nochromium` should get you to an empty screen with changing backgrounds. Again, this is not a place to complain about issues with the base game.
