### ISSUE TITLE
Could you clarify instructions?

### ISSUE THREAD

**Issue by BandyRocket** [robotboy655/gmod-lua-menu#25]
I'm having trouble understanding your instructions, and I can't get the menu to even work. If you could clarify or make your instructions more detailed, or maybe even create a video that would help me out a ton. I'm on Mac Monterey if that helps at all.

**Comment by BandyRocket** [comment]
https://drive.google.com/file/d/1YHZ5qCKWPSE0W9Z48rXyXNp7Mp2p2Vvj/view?usp=sharing
heres a video that shows what's happening

**Comment by robotboy655** [comment]
I don't know how I can make the instructions more clear than they already are. You did it wrong though.

The main page says this:
To install this, download the ZIP and extract contents of `gmod-lua-menu-master` folder ( folders `lua` and `materials` ) to your `SteamApps/common/GarrysMod/garrysmod/` folder.

But you for some unknown reason extracted `gmod-lua-menu-master` to your `addons/` folder which the guide does not tell you do to.
