### ISSUE TITLE
Hi, I can't spawn dupes and load saves

### ISSUE THREAD

**Issue by PrabhatkumarGaming** [robotboy655/gmod-lua-menu#27]
Hi, Im on MacOS Monterey and i had to install this for the game to launch. After i did, i couldn’t spawn dupes or load saves. the saves menu in the spawnmenu is empty, and i have started heavily using dupes because i'm making wiremod creations and saving them because i dont wanna keep making them whenever i want them. Please help.

**Comment by robotboy655** [comment]
It's not part of this addon. You have disabled the game system (web browser) that is required to see the dupe/save menus. Check the original github issue for a better solution for your problem.

**Comment by SpaceN64** [comment]
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
