### ISSUE TITLE
Saves & Dupes not showing

### ISSUE THREAD

**Issue by Spritzerland** [robotboy655/gmod-lua-menu#29]
In the spawnmenu, the saves and dupes are not showing at all. Nothing in console

**Comment by robotboy655** [comment]
This mod does not modify or replace any parts of the spawnmenu. The issue you are having is not related to this mod.

**Comment by SpaceN64** [comment]
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.

**Comment by OpenSauce04** [comment]
> found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.

This didn't work for me, and neither did leaving the chromium beta entirely. It seems like the underlying issue is the same as the reason I needed to use this lua menu in the first place.
