### ISSUE TITLE
yo where the zip go?

### ISSUE THREAD

**Issue by GodsBadAssBlade** [robotboy655/gmod-lua-menu#30]
where it be?

**Comment by L1Q** [comment]
You are old enough now to zip it up yourself!
Go on, just don't rush it or you can hurt your... oh no, not the flashbacks!

Anyway, just go to the [main page](https://github.com/robotboy655/gmod-lua-menu), and click on the green "Code" button... wait what?? There is a "Download ZIP" option right there?? No way!
![image](https://user-images.githubusercontent.com/6942070/175808274-66588ab9-d84a-4774-98b9-f5d0dedabd29.png)
