### ISSUE TITLE
Dupes not working

### ISSUE THREAD

**Issue by elizabethlink1245** [robotboy655/gmod-lua-menu#36]
im attempting to spawn dupes into the game however even if they are saved in my gmod's folder they won't load in the dupe menu in game

**Comment by robotboy655** [comment]
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/29

**Comment by SpaceN64** [comment]
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
