### ISSUE TITLE
No dupes menu

### ISSUE THREAD

**Issue by bedrockperson** [robotboy655/gmod-lua-menu#38]
<img width="1440" alt="Screen Shot 2022-10-10 at 4 01 31 PM" src="https://user-images.githubusercontent.com/87041048/194943531-1efc279d-6570-4250-8c03-1c73ba80da8e.png">

Exactly what it says on the tin – no dupes. 

Using this menu is literally the only way I can use GMOD so I tried to make peace with the lack of saves, but dupes too? IDK if this is a separate issue or if this is also a lack of save menu. Really really hope somehow a miracle happens and we get a save and dupe update.

**Comment by bedrockperson** [comment]
> Duplicate of #29

Alright I see, do you have any recommendations as to where to go from here, though? Because the saves and dupes show up fine without the Lua menu, and then when Lua menu is installed, they disappear. It's clearly related.

**Comment by SpaceN64** [comment]
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
