### ISSUE TITLE
New Game menu completely broken.

### ISSUE THREAD

**Issue by Tenrys** [robotboy655/gmod-lua-menu#4]
Clicking a gamemode does nothing, no back button.

![asd](http://tenrys.montoyo.net/ShareX/2015-05-03_06-45-49.png)

**Comment by robotboy655** [comment]
You'll need to provide more info than that. Like console log and game version. As far as I am concerned, you are using old version of the menu or the newest version may not be compatible with non-dev GMod.

**Comment by Tenrys** [comment]
I can't open console. Non-dev GMod and latest version of menu.

**Comment by robotboy655** [comment]
Well then I cant help you. Either try Dev GMod or wait for the update.
