### ISSUE TITLE
Can't browse any Dupes or Saves

### ISSUE THREAD

**Issue by kor4yg** [robotboy655/gmod-lua-menu#43]
Saves or Dupes are not displayed. The Saves and Dupes menus are completely blank.

**Comment by robotboy655** [comment]
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/29

**Comment by SpaceN64** [comment]
found out whats wrong, basically what you want to do is get rid of the "-nochromium". the game will launch, and the dupe and saves menu will show.
