### ISSUE TITLE
Abnormal display

### ISSUE THREAD

**Issue by Ponkichi23** [robotboy655/gmod-lua-menu#46]
Hello, can you tell me how to fix this issue?
<img width="1440" alt="Screenshot 2023-06-24 at 12 05 58 PM" src="https://github.com/robotboy655/gmod-lua-menu/assets/122189884/50b463bd-075e-4846-8ada-6699961b516f">

**Comment by robotboy655** [comment]
Duplicate of https://github.com/robotboy655/gmod-lua-menu/issues/32
