### ISSUE TITLE
Permanent blue screen on mac

### ISSUE THREAD

**Issue by Probablyhuman23** [robotboy655/gmod-lua-menu#48]
I know that this might get tagged as a copy of #26 but the solution given to that user hasn’t worked for me for some reason.
I know it is these files causing the problem because the game opened fine before installing them I just didn’t have any menu ui but I got a permanent blue screen after installing them

Any solution is helpful but I’d prefer one that works

**Comment by Probablyhuman23** [comment]
![Uploading image.jpg…]()

**Comment by robotboy655** [comment]
If its "these files" causing the problem, just delete them and verity your game cache.
