### ISSUE TITLE
game and language buttons not present on the gmod menu

### ISSUE THREAD

**Issue by themysterioushobosmgf** [robotboy655/gmod-lua-menu#52]
idk how but it just... happened, im not sure if it was the cause of me editing the lua files but yeah, does anyone know how to revert it?

![image](https://github.com/user-attachments/assets/f9e1597a-93a9-4529-95f0-e265f7371f24)

**Comment by robotboy655** [comment]
Try opening your console (SHIFT+ESC or `) and see if there are any errors there.

**Comment by themysterioushobosmgf** [comment]
theres a couple of em
![image](https://github.com/user-attachments/assets/eb353964-a742-424e-bc75-a3c04db72f2e)

**Comment by robotboy655** [comment]
Validate your game using Steam reinstall the menu. That should fix the missing function from the base game. Do not modify the game files yourself unless you know what you are doing.

**Comment by themysterioushobosmgf** [comment]
good idea
